# Generated by Django 4.0.5 on 2022-11-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_author_blogger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='blogger',
        ),
    ]
