# Generated by Django 4.0.5 on 2022-11-14 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
